import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
export const baseUrl = "http://localhost:3008";
// export const baseUrl = "https://";

// Define base API configuration
export const apiSlice = createApi({
    reducerPath: 'api', // unique key in store
    baseQuery: fetchBaseQuery({ baseUrl: baseUrl }),

    tagTypes: ["User", "Product", "Payment", "Sales"],

    endpoints: (builder) => ({
        // User
        login: builder.mutation({
            query: (data) => ({
                url: '/user/login',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["User"]
        }),

        //Product
        getProducts: builder.query({
            query: ({ page, limit }) => `/product?page=${page}&limit=${limit}`,
            providesTags: ["Product"]
        }),

        addProduct: builder.mutation({
            query: (data) => ({
                url: '/product',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["Product"]
        }),

        updateProduct: builder.mutation({
            query: ({ id, data }) => ({
                url: `/product/${id}`,
                method: 'PATCH',
                body: data,
            }),
            invalidatesTags: ["Product"]
        }),

        deleteProduct: builder.mutation({
            query: (id) => ({
                url: `/product/${id}`,
                method: 'DELETE',
            }),
            invalidatesTags: ["Product"]
        }),

        //Sales
        addSales: builder.mutation({
            query: (data) => ({
                url: '/sales',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["Sales"]
        }),

        //Payment
        addPayment: builder.mutation({
            query: (data) => ({
                url: '/payment',
                method: 'POST',
                body: data,
            }),
            invalidatesTags: ["Payment"]
        }),
    }),
});

// Export hooks auto-generated by RTK Query
export const {
    useLoginMutation,
    useGetProductsQuery,
    useAddProductMutation,
    useDeleteProductMutation,
    useUpdateProductMutation,
    useAddSalesMutation,
    useAddPaymentMutation,
} = apiSlice;
